version: '3.8'
services:
  neo4j:
    image: neo4j:5.21.2-enterprise
    container_name: neo4j
    hostname: neo4j
    environment:
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
      NEO4J_AUTH: "none"
    ports:
      - "7474:7474"
      - "7687:7687"
      - "2004:2004"
