consul-up:
	docker-compose -f ./consul/docker-compose.yml up --remove-orphans -d

consul-down:
	docker-compose -f ./consul/docker-compose.yml down -v

etcd-up:
	docker-compose -f ./etcd/docker-compose.yml up --remove-orphans -d

etcd-down:
	docker-compose -f ./etcd/docker-compose.yml down -v
