version: '3.8'

services:
  consul-server-1:
    image: hashicorp/consul:1.14.3
    container_name: consul-server-1
    hostname: consul-server-1
    restart: always
    volumes:
      - ./config/consul-server-1.json:/consul/config/consul-server-1.json:ro
#      - ./certs/:/consul/config/certs/:ro
    networks:
      - consul
    ports:
      - "8501:8500"
      - "8601:8600/tcp"
      - "8601:8600/udp"
    command: "agent -server -bootstrap-expect 3 -ui -client 0.0.0.0"

  consul-server-2:
    image: hashicorp/consul:1.14.3
    container_name: consul-server-2
    hostname: consul-server-2
    restart: always
    volumes:
      - ./config/consul-server-2.json:/consul/config/consul-server-2.json:ro
#      - ./certs/:/consul/config/certs/:ro
    networks:
      - consul
    ports:
      - "8502:8500"
      - "8602:8600/tcp"
      - "8602:8600/udp"
    command: "agent -server -join consul-server-1"

  consul-server3:
    image: hashicorp/consul:1.14.3
    container_name: consul-server-3
    hostname: consul-server-3
    restart: always
    volumes:
      - ./config/consul-server-3.json:/consul/config/consul-server-3.json:ro
#      - ./certs/:/consul/config/certs/:ro
    networks:
      - consul
    ports:
      - "8503:8500"
      - "8603:8600/tcp"
      - "8603:8600/udp"
    command: "agent -server -join consul-server-1"

networks:
  consul:
    driver: bridge
