compose-up:
	docker-compose -f docker-compose.yml up --remove-orphans -d

compose-down:
	docker-compose -f docker-compose.yml down

mongosh:
	docker exec -it mongodb mongosh --username "root" --password "example"
