version: '3.8'
services:
  clickhouse:
    image: clickhouse/clickhouse-server:23.8
    container_name: clickhouse
    hostname: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./clickhouse/clickhouse.sql:/docker-entrypoint-initdb.d/init.sql
      - ./clickhouse:/clickhouse
      - volume_clickhouse:/var/lib/clickhouse

volumes:
  volume_clickhouse:
